# Generated by Django 5.1.15 on 2026-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="is_template",
            field=models.BooleanField(
                default=False, help_text="Template runs are used as blueprints for creating new runs"
            ),
        ),
    ]
