# Generated by Django 5.1.15 on 2026-03-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0002_run_is_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="color",
            field=models.CharField(blank=True, default="", help_text="Hex color code, e.g. #3B82F6", max_length=7),
        ),
    ]
