# Generated by Django 5.1.15 on 2026-03-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_add_house_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Hex border color, e.g. #FFD700', max_length=7),
        ),
    ]
