# Generated by Django 5.1.15 on 2026-04-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_add_year_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='theme_accent',
            field=models.CharField(blank=True, default='', help_text='Accent color (gold)', max_length=7),
        ),
        migrations.AddField(
            model_name='run',
            name='theme_nav_bg',
            field=models.CharField(blank=True, default='', help_text='Navigation background', max_length=7),
        ),
        migrations.AddField(
            model_name='run',
            name='theme_page_bg',
            field=models.CharField(blank=True, default='', help_text='Page background', max_length=7),
        ),
        migrations.AddField(
            model_name='run',
            name='theme_text',
            field=models.CharField(blank=True, default='', help_text='Primary text color', max_length=7),
        ),
    ]
