# Generated by Django 5.1.15 on 2026-03-19 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casting", "0001_initial"),
        ("runs", "0002_run_is_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casting",
            name="teaching_subjects",
        ),
        migrations.AddField(
            model_name="casting",
            name="teaching_subject",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="runs.teachingsubject"
            ),
        ),
    ]
