# Generated by Django 5.1.15 on 2026-03-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0002_remove_casting_teaching_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casting',
            name='allow_multiple_posts',
            field=models.BooleanField(default=False, help_text='Allow this player to create multiple character introduction posts (e.g. split personality).'),
        ),
    ]
