# Generated by Django 5.1.15 on 2026-03-19 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("runs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("professor", "Professor"),
                            ("staff", "Staff"),
                            ("headmaster", "Headmaster"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("character_name", models.CharField(blank=True, max_length=300)),
                ("staff_title", models.CharField(blank=True, max_length=300)),
                ("custom_attributes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blood_status",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="runs.bloodstatus"
                    ),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invites_claimed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("clubs", models.ManyToManyField(blank=True, to="runs.club")),
                (
                    "house",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="runs.house"
                    ),
                ),
                (
                    "monitor_of_club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="runs.club",
                    ),
                ),
                (
                    "monitor_of_house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="runs.house",
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="runs.path"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="runs.run"
                    ),
                ),
                ("teaching_subjects", models.ManyToManyField(blank=True, to="runs.teachingsubject")),
                (
                    "year",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="runs.year"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("professor", "Professor"),
                            ("staff", "Staff"),
                            ("headmaster", "Headmaster"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("character_name", models.CharField(blank=True, max_length=300)),
                ("staff_title", models.CharField(blank=True, max_length=300)),
                ("custom_attributes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blood_status",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="runs.bloodstatus"
                    ),
                ),
                ("clubs", models.ManyToManyField(blank=True, to="runs.club")),
                (
                    "house",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="runs.house"
                    ),
                ),
                (
                    "invite",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership",
                        to="invites.invite",
                    ),
                ),
                (
                    "monitor_of_club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="runs.club",
                    ),
                ),
                (
                    "monitor_of_house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="runs.house",
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="runs.path"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="runs.run"
                    ),
                ),
                ("teaching_subjects", models.ManyToManyField(blank=True, to="runs.teachingsubject")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="runs.year"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "run")},
            },
        ),
    ]
